name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job for building and testing the .NET API
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Use the .NET version you need

      - name: Restore dependencies
        run: |
          cd Server
          dotnet restore MarketPulse.Api/MarketPulse.Api.csproj

      - name: Build
        run: |
          cd Server
          dotnet build --configuration Release MarketPulse.Api/MarketPulse.Api.csproj

  # Job for building and testing the React client
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify Node.js version compatible with your project

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

